#Yaml file for trajectory params

homework2: #namespace for the whole package
  fig8:    #namespace for figure eight functionality
    width: 1 # width of figure 8
    height: 1 # height of figure 8
    period: 30 # number of seconds to complete 
  